
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Dec 18 2025 10:57:30 EST (Dec 18 2025 15:57:30 UTC)

// Verification Directory fv/vendingmachine 

module vendingmachine(choco_out, chng_out, clk, reset, two_in, one_in);
  input clk, reset, two_in, one_in;
  output choco_out, chng_out;
  wire clk, reset, two_in, one_in;
  wire choco_out, chng_out;
  wire [2:0] state;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_16;
  wire n_18, n_19, sel;
  OAI32X1 g749__2398(.A0 (state[0]), .A1 (state[2]), .A2 (n_9), .B0
       (two_in), .B1 (n_12), .Y (n_18));
  DFFNSRXL sel_reg(.RN (1'b1), .SN (1'b1), .CKN (clk), .D (n_14), .Q
       (sel), .QN (UNCONNECTED));
  NOR2XL g753__5107(.A (state[2]), .B (n_13), .Y (n_16));
  BUFX3 g756(.A (n_14), .Y (choco_out));
  CLKINVX1 g757(.A (n_8), .Y (n_14));
  AOI21XL g758__6260(.A0 (one_in), .A1 (n_2), .B0 (n_6), .Y (n_13));
  AOI31X1 g754__4319(.A0 (n_7), .A1 (n_5), .A2 (one_in), .B0 (n_10), .Y
       (n_12));
  NOR2BX1 g755__8428(.AN (n_10), .B (n_9), .Y (n_11));
  AOI31X1 g759__5526(.A0 (state[0]), .A1 (state[1]), .A2 (n_7), .B0
       (n_3), .Y (n_8));
  NOR2BX1 g760__6783(.AN (n_5), .B (n_9), .Y (n_6));
  BUFX2 g761(.A (n_3), .Y (chng_out));
  NOR3X1 g762__3680(.A (state[0]), .B (state[1]), .C (n_7), .Y (n_3));
  NOR3X1 g763__1617(.A (state[1]), .B (state[2]), .C (n_0), .Y (n_10));
  NOR2XL g766__2802(.A (state[0]), .B (n_1), .Y (n_5));
  NOR2XL g764__1705(.A (state[1]), .B (two_in), .Y (n_2));
  NAND2BX1 g765__5122(.AN (one_in), .B (two_in), .Y (n_9));
  NOR2XL g767__8246(.A (sel), .B (reset), .Y (n_19));
  DFFRX1 \state_reg[1] (.RN (n_19), .CK (clk), .D (n_16), .Q
       (state[1]), .QN (n_1));
  DFFRX1 \state_reg[0] (.RN (n_19), .CK (clk), .D (n_18), .Q
       (state[0]), .QN (n_0));
  DFFRX1 \state_reg[2] (.RN (n_19), .CK (clk), .D (n_11), .Q
       (state[2]), .QN (n_7));
endmodule

